### ISSUE TITLE
error while trying to run bot

### ISSUE THREAD

**Issue by virginsince1997** [mpawlak2/instalike-instagram-bot#16]
i got an error while trying to login
i ran with with the python34 module
my credentials are correct
> Using default.cfg file.
WARNING! bot is working whole time, be careful because leaving it running for too long time may result in blocked account.
working whole time.
Trying to log in ...
Check credentials, also try to log in to your account manually to check if everything is fine then retry.
Oops! could not log in.
failed to log in wait for 5min

**Comment by mpawlak2** [comment]
@virginsince1997 what OS do you use?

**Comment by virginsince1997** [comment]
Windows, The username resets even after I have saved it

**Comment by virginsince1997** [comment]
@mpawlak2 its working now thanks , but its not liking my feeds

**Comment by virginsince1997** [comment]
@mpawlak2 Thank you very much it works , id be sure to donate when i can , i appreciate.
