### ISSUE TITLE
postgresql.exception.UndefinedFunctionError: function merge_photo(...) does not exist

### ISSUE THREAD

**Issue by tim-peters** [mpawlak2/instalike-instagram-bot#18]
Any idea why this happens?
![image](https://cloud.githubusercontent.com/assets/1482203/18961905/e71b818a-866e-11e6-8846-48958248631e.png)

**Comment by thenayr** [comment]
You need to import the database like so:

psql -h localhost -U postgres -d your-database-name < db_setup.sql

**Comment by tim-peters** [comment]
My bad. I didn't notice that the import was not successful earlier.
Thanks! Great work btw!
