### ISSUE TITLE
Failed likes

### ISSUE THREAD

**Issue by chinciusan** [mpawlak2/instalike-instagram-bot#19]
Why do I get "failed likes: 17" ? 
No successful like yet. Have I missed anything?

**Comment by mpawlak2** [comment]
Hello, this is first time you use it? Try to log in to your account with app/website and try liking photo, is everything working??

**Comment by chinciusan** [comment]
Hi. Yes, it's the first time, I'm using it. Everything is working on the website and app.

**Comment by mpawlak2** [comment]
@chinciusan Fixed that, thanks;)
