### ISSUE TITLE
NEED HELP! HELP ME

### ISSUE THREAD

**Issue by verobin2237** [mpawlak2/instalike-instagram-bot#31]
python3 main.py -u xxx -p xxx
Using default.cfg file.
WARNING! bot is working whole time, be careful because leaving it running for too long time may result in blocked account.
working whole time.
Trying to log in ...
code: 400, could not POST: https://www.instagram.com/accounts/login/?force_classic_login&hl=pl
Oops! could not log in.
failed to log in wait for 5min
Trying to log in ...
code: 400, could not POST: https://www.instagram.com/accounts/login/?force_classic_login&hl=pl
Oops! could not log in.
failed to log in wait for 5min
Trying to log in ...
code: 400, could not POST: https://www.instagram.com/accounts/login/?force_classic_login&hl=pl
Oops! could not log in.
failed to log in wait for 5min

then i get  this on mah phone

![27848283_1991583887767474_58998860_n](https://user-images.githubusercontent.com/30985549/35778805-bf826306-09ed-11e8-824e-39e46a537404.png)

**Comment by verobin2237** [comment]
i get this everytime i run it ...even after clicking "this was me" :((

**Comment by verobin2237** [comment]
and also forgot to say... i ran it through PythonAnywhere Bash
console

**Comment by Radren** [comment]
I suppose, Instagram blocked you because server of PythonAnywhere locate in unusual location for you. What happend when you pressed "This was me" button?

**Comment by verobin2237** [comment]
well the script didnt run ..it stopped
Pressing the "This was me" button didnt help
it kept on popping up every time i run the script even after pressing This Was Me button

**Comment by mpawlak2** [comment]
@verobin2237 Yeah the problem is with location of PythonAnywhere servers, which are problably far from you. Just use it on your computer/buy vps near your real location and you should be fine. Sorry for misleading you with info in readme, it used to work..
