### ISSUE TITLE
Is database SQL up to date

### ISSUE THREAD

**Issue by Inlife** [mpawlak2/instalike-instagram-bot#8]
Hey,

I just wanted to sure, is the `db_setup.sql` is up to date. 
Because on fresh clone+db setup, right just after launch i ran onto this problem everytime:
> postgresql.exceptions.UndefinedTableError: relation "unfollow_queue" does not exist

With enabled database management, of course.

Is it possible to be outdated, or am i doing something wrong?

Thank you! 👍 

P.S. using this awesome thing almost everyday, niceee! 😎 😄 👍

**Comment by mpawlak2** [comment]
Hello,

it should be fine now, added missing relation to db_setup.sql, if you still have problems running it - let me know!

Thanks for interest:)

**Comment by Inlife** [comment]
Working like a charm! 👍 

Thank you! 😄
