### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Revod** [mpawlak2/instalike-instagram-bot#9]
Hi, When I try to run get this... How to fix that? thanks 
![image](https://cloud.githubusercontent.com/assets/10109689/17869614/0545685c-6882-11e6-86d9-4ecf710af971.png)

**Comment by mpawlak2** [comment]
Hello, will look into this today:)

Thanks for interest!

**Comment by Alvian911** [comment]
The error same with me

**Comment by mpawlak2** [comment]
Changed header value to string, not sure that caused error since i could not reproduce it. Could you guys verify that please?:)

**Comment by Revod** [comment]
@mpawlak2 Where I need to change the header to string? (sorry for my noob question)

**Comment by mpawlak2** [comment]
@Revod Just update your local repository from github

**Comment by Revod** [comment]
Problem Fixed, thanks

**Comment by Revod** [comment]
One last question 
![image](https://cloud.githubusercontent.com/assets/10109689/17894523/a1debc8c-6917-11e6-9231-ecf72879aa75.png) now the bot are running, how time need to pass to start to following? I still seeing the same _Following_ in my instagram account

**Comment by mpawlak2** [comment]
So you have this option in defaut.cfg file - WorkWholeTime, if set to false bot will pick random periods of time to work in, and as it says bot will start in 373minutes  more or LESS 7 hours 
if you want bot to start immediately set WorkWholeTime to True
